services:
  dl-wx-updater:
    build: .
    container_name: dl-wx-updater
    network_mode: host
    environment:
      - TZ=Pacific/Auckland
      - API_URL=https://api.metservice.com/mobile/nz/weatherData
      - API_KEY=apikey
      - LAT=-45.87416
      - LON=170.50361
      - CAMERA_URL=http://192.168.53.4/SetImageOsdConfig
      - CAMERA_USERNAME=admin
      - CAMERA_PASSWORD=dumbpassword
      - UPDATE_INTERVAL=600
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
